GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzI0NDc4NjYzLCJleHAiOjE3MjQ0Nzk1NjN9.4mQq6EWJPTAQEPoBUOo1rKeHs-GkujVSaiAO1mhGOVM

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzI0NDc4NjYzLCJleHAiOjE3MjQ0Nzk1NjN9.4mQq6EWJPTAQEPoBUOo1rKeHs-GkujVSaiAO1mhGOVM"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzI0NDc4NjE5fQ.1qpzuTC7u_ZBs8vHjjpIM0IvYVX76FbeOo-SNXoruMs"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}